import {
  Baby,
  Banknote,
  BedDouble,
  Beer,
  Bike,
  Bitcoin,
  Book,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  CarFront,
  Cat,
  Church,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  Cross,
  Dog,
  Drill,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Handshake,
  HeartPulse,
  Home,
  Hospital,
  IceCream,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  Mic,
  Monitor,
  Music,
  Palette,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Plug,
  Popcorn,
  Receipt,
  RefreshCcw,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Ticket,
  Train,
  TrendingUp,
  Trophy,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
} from 'lucide-react';
import { cn } from '@/lib/utils';

type IconComponent = React.ComponentType<{ className?: string }>;

/**
 * Icon keys are stored on category documents, so they must stay stable.
 * Add new keys freely; never rename or remove an existing one.
 */
export const categoryIconGroups: { label: string; icons: Record<string, IconComponent> }[] = [
  {
    label: 'Home & bills',
    icons: {
      housing: Home,
      rent: Building2,
      utilities: Plug,
      internet: Wifi,
      phone: Smartphone,
      furniture: Sofa,
      repairs: Wrench,
      tools: Drill,
      insurance: Shield,
      bills: Receipt,
      lighting: Lightbulb,
    },
  },
  {
    label: 'Food & drink',
    icons: {
      groceries: ShoppingCart,
      restaurants: UtensilsCrossed,
      coffee: Coffee,
      bar: Beer,
      wine: Wine,
      sweets: IceCream,
      bakery: Cake,
    },
  },
  {
    label: 'Transport',
    icons: {
      transportation: Bus,
      car: Car,
      taxi: CarFront,
      fuel: Fuel,
      train: Train,
      bike: Bike,
      flights: Plane,
      travel: Luggage,
      hotel: BedDouble,
    },
  },
  {
    label: 'Life & health',
    icons: {
      health: HeartPulse,
      doctor: Stethoscope,
      pharmacy: Pill,
      hospital: Hospital,
      'personal-care': Sparkles,
      haircut: Scissors,
      fitness: Dumbbell,
      clothing: Shirt,
      shopping: ShoppingBag,
      jewelry: Gem,
      kids: Baby,
      pets: PawPrint,
      dog: Dog,
      cat: Cat,
    },
  },
  {
    label: 'Leisure & learning',
    icons: {
      entertainment: Clapperboard,
      movies: Popcorn,
      games: Gamepad2,
      music: Music,
      concerts: Mic,
      instruments: Guitar,
      events: Ticket,
      sports: Trophy,
      hobbies: Palette,
      education: GraduationCap,
      books: Book,
      subscriptions: RefreshCcw,
      tech: Laptop,
      office: Monitor,
    },
  },
  {
    label: 'Money & giving',
    icons: {
      salary: Briefcase,
      freelance: Handshake,
      interest: Percent,
      investments: TrendingUp,
      crypto: Bitcoin,
      savings: PiggyBank,
      bank: Landmark,
      cash: Banknote,
      wallet: Wallet,
      loan: HandCoins,
      fees: Coins,
      refund: Undo2,
      gifts: Gift,
      charity: HandHeart,
      donation: Church,
      taxes: Cross,
      eco: Leaf,
      other: CircleDollarSign,
    },
  },
];

const icons: Record<string, IconComponent> = Object.fromEntries(
  categoryIconGroups.flatMap((group) => Object.entries(group.icons)),
);

export const categoryIconNames = Object.keys(icons);

export function CategoryIcon({ icon, className }: { icon?: string; className?: string }) {
  const Icon = icons[icon ?? 'other'] ?? CircleDollarSign;
  return <Icon className={cn('size-4', className)} aria-hidden="true" />;
}
